git:
  commitMessage: "chore(release): v${version}"
  tagAnnotation: "chore(release): v${version}"
  tagName: "v${version}"

hooks:
  after:bump:
    - "npm run changelog:update"
    - rm -rf lib
    - "npm publish"

# automatic publish from github workflow
npm:
  publish: false
  private: true
  registry: "OMITTED"
